// DO NOT EDIT THIS FILE OUTSIDE OF BACKEND

import { hash, verify } from "argon2";
import { filter, pool } from "./database";
import { decrypt, encrypt } from "./encrypt";
import { z } from "zod";
import { passwordRegex, User, usernameRegex } from "./types";
import { randomInt } from "crypto";

const saltLength = 20;

/**
 * @returns Random salt of length saltLength
 */
function randomSalt() {
    return Array(saltLength).fill(0).map(() => String.fromCharCode(Math.floor(Math.random() * 95) + 32)).join("");
}

export interface AuthResponse {
  success: boolean;
  message: string;
};

export interface UserAuthRow {
    user_id: number;
    password_hash: string;
    salt: string;
    username: string;
    disabled: boolean;
};

export const defaultUser: User = {user_id: 0, username: "", disabled: false};
export function getGuestUser() {
    const user_id = -randomInt(1e7, 1e8);
    return {...defaultUser, user_id, username: `Guest ${-user_id}`}
}

export function isGuest(user: User) {
    return user.user_id < 0;
}

export function getNextTokenExpiration() {
    return Date.now() + 30 * 24 * 60 * 60 * 1000;
}

export function generateAuthToken(user_id: number, password_hash: string) {
    const token: AuthToken = { user_id, password_hash, expires: getNextTokenExpiration() };
    return encrypt(JSON.stringify(token));
}

export async function recaptchaIsGood(captcha: string, action: string) {
    const result = await fetch("https://www.google.com/recaptcha/api/siteverify", {
        method: "POST",
        headers: {
            "Content-Type": "application/x-www-form-urlencoded"
        },
        body: new URLSearchParams({
            secret: process.env.CAPTCHA_SECRET_KEY!,
            response: captcha
        }).toString()
    }).then(res => res.json());
    console.log("Recaptcha:", result);
    return result.success && result.action === action && result.score >= .7;
}

async function getHash(password: string, salt: string) {
    return await hash(password + salt);
}

const usernameChecker = z.string().regex(usernameRegex);
const passwordChecker = z.string().regex(passwordRegex);

export async function signUp(username: string, password: string, captcha: string): Promise<AuthResponse> {
    // Make sure username and password are valid
    try {
        usernameChecker.parse(username);
        passwordChecker.parse(password);
    } catch (e) {
        return { success: false, message: "Invalid username or password" };
    }

    if (filter.isProfane(username))
        return { success: false, message: `Cannot use this username. Maybe try ${filter.clean(username)}?` };

    // Make sure captcha is good
    if (!await recaptchaIsGood(captcha, "signup"))
        return { success: false, message: "Try recaptcha again" };

    const rows: UserAuthRow[] = (await pool.query("SELECT * FROM user_auth WHERE username = $1", [username])).rows;
    // Make sure username is not already taken
    if (rows.length > 0)
        return { success: false, message: "Username already taken" };

    const salt = randomSalt();
    const password_hash = await getHash(password, salt);
    const user_id = (await pool.query("INSERT INTO user_auth VALUES (DEFAULT, $1, $2, $3, false) RETURNING user_id", [password_hash, salt, username])).rows[0].user_id;
    await pool.query("INSERT INTO user_data VALUES ($1)", [user_id]);

    return { success: true, message: generateAuthToken(user_id, password_hash) }
}

export async function signIn(username: string, password: string): Promise<AuthResponse> {
    // Make sure username and password are valid
    try {
        usernameChecker.parse(username);
        passwordChecker.parse(password);
    } catch (e) {
        return { success: false, message: "Invalid username or password" };
    }

    const rows: UserAuthRow[] = (await pool.query("SELECT * FROM user_auth WHERE username = $1", [username])).rows;
    // Return error if no user found or password does not match
    if (rows.length === 0 || !await verify(rows[0].password_hash, password + rows[0].salt))
        return { success: false, message: "Invalid username or password" };

    return { success: true, message: generateAuthToken(rows[0].user_id, rows[0].password_hash) };
}

export interface AuthToken {
    user_id: number;
    password_hash: string;
    expires: number;
};

export async function isValidToken(token?: string): Promise<false | User> {
    // If empty or falsy token, return false
    if (!token)
        return false;
    const data: AuthToken = JSON.parse(decrypt(token));
    if (data.expires < Date.now())
        return false;
    const rows = (await pool.query("SELECT user_id, username, disabled FROM user_auth WHERE user_id = $1 AND password_hash = $2", [data.user_id, data.password_hash])).rows;
    return rows.length > 0 && rows[0];
}
