// DO NOT EDIT THIS FILE OUTSIDE OF BACKEND

// UTIL
import seedrandom from "seedrandom";
import { randomSeed } from "./Base64";
import {
  AnswerJudgement,
  ModeData,
  ModeQuestion,
  Question,
  QuestionGenerator,
} from "./types";

const primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47];

const polygonStrs = [
  "",
  "",
  "",
  "triangular",
  "square",
  "pentagonal",
  "hexagonal",
  "heptagonal",
  "octagonal",
  "nonagonal",
  "decagonal",
  "hendecagonal",
  "dodecagonal",
];

const months = [
  "Jan.",
  "Feb.",
  "Mar.",
  "Apr.",
  "May",
  "Jun.",
  "Jul.",
  "Aug.",
  "Sep.",
  "Oct.",
  "Nov.",
  "Dec.",
];

const romans: { [key: number]: string } = {
  1000: "M",
  900: "CM",
  500: "D",
  400: "CD",
  100: "C",
  90: "XC",
  50: "L",
  40: "XL",
  10: "X",
  9: "IX",
  5: "V",
  4: "IV",
  1: "I",
};

const names = [
  "",
  "one",
  "two",
  "three",
  "four",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
];

const tens = [
  "",
  "",
  "twenty",
  "thirty",
  "forty",
  "fifty",
  "sixty",
  "seventy",
  "eighty",
  "ninety",
];

// For unit conversion, 2 is for estimation
const units = [
  ["fathoms", "feet"],
  ["rods", "feet"],
  ["mph", "ft/s"],
  ["square miles", "acres"],
  ["fluid ounces", "gallons"],
  ["cups", "gallons"],
];
const convs = [
  [1, 6],
  [2, 33],
  [15, 22],
  [1, 640],
  [128, 1],
  [16, 1],
];
const units2 = [
  ["gallons", "cubic inches"],
  ["leagues of land", "acres"],
  ["varas", "yards"],
  ["varas", "inches"],
  ["chains", "feet"],
  ["caballerias", "acres"],
  ["labor", "square varas"],
];
const convs2 = [
  [1, 231],
  [1, 4428.4],
  [1, 0.925926],
  [1, 33.333333],
  [1, 66],
  [1, 108],
  [1, 1000],
];
for (let i = 0; i < units.length; i++) {
  units2.push(units[i]);
  convs2.push(convs[i]);
}

export const getSeed = (querySeed?: string) => querySeed ?? randomSeed();

export class RNG {
  rng: seedrandom.PRNG;
  seed: string;
  constructor(seed: string = randomSeed()) {
    this.seed = seed;
    this.rng = seedrandom(seed);
  }

  // Random [0, 1)
  random() {
    return this.rng();
  }

  // Inclusive random
  randomInt(min: number, max: number) {
    return Math.floor(this.random() * (max - min + 1)) + min;
  }
}

const gcd = (a: number, b: number) => {
  if (!b) {
    return a;
  }
  return gcd(b, a % b);
};

const binaryExp = (base: number, exp: number, mod: number): number => {
  if (exp === 0) {
    return 1;
  }
  if (exp % 2 === 1) {
    return (base * binaryExp(base, exp - 1, mod)) % mod;
  }
  const half = binaryExp(base, exp / 2, mod);
  return (half * half) % mod;
};

export const getNumberRankStr = (n: number) => {
  switch (n) {
    case 1:
      return `${n}st`;
    case 2:
      return `${n}nd`;
    case 3:
      return `${n}rd`;
    default:
      return `${n}th`;
  }
};

export const toRoman = (n: number) => {
  let str = ``;
  const keys = Object.keys(romans).map(Number);
  for (let i = keys.length - 1; i >= 0; i--) {
    const key = keys[i];
    while (n >= key) {
      str += romans[key] as any;
      n -= key;
    }
  }
  return str;
};

export const joinAdd = (arr: number[] | string[]) => {
  if (arr.length === 1) return arr[0];
  // Make sure to only include + if this number is positive, otherwise - is already included
  return arr
    .map(
      (x, i) =>
        `${
          i > 0 && (typeof arr[i] == "string" ? parseFloat(arr[i]) : arr[i]) > 0
            ? "+"
            : ""
        }${x}`
    )
    .join(" ");
};

class Fraction {
  numerator: number;
  denominator: number;
  constructor(numerator: number, denominator: number) {
    this.numerator = numerator;
    this.denominator = denominator;
    this.simplify();
  }

  getWhole() {
    return Math.floor(Math.abs(this.numerator) / this.denominator);
  }

  hasFrac() {
    return this.numerator % this.denominator !== 0;
  }

  isMixed() {
    return this.getWhole() !== 0;
  }

  getMixed() {
    const whole = this.getWhole();
    return {
      whole: whole,
      frac: new Fraction(
        Math.abs(this.numerator) % this.denominator,
        this.denominator
      ),
    };
  }

  simplify() {
    const _gcd_ = gcd(Math.abs(this.numerator), this.denominator);
    this.numerator /= _gcd_;
    this.denominator /= _gcd_;
    if (this.denominator < 0) {
      this.numerator *= -1;
      this.denominator *= -1;
    }
  }

  formatted({
    useImproper,
    overrideNum,
    overrideDenom,
    overrideMixed,
  }: {
    useImproper?: boolean;
    overrideNum?: number;
    overrideDenom?: string;
    overrideMixed?: string;
  } = {}) {
    const num = overrideNum ?? this.numerator;
    if (num == 0) return "0";
    const sign = num < 0 ? "-" : "";
    if (this.isMixed() && !useImproper) {
      const mixed = this.getMixed();
      // if (useLatex)
      //   return `${sign}${overrideMixed ?? mixed.whole} \\frac{${overrideNum ?? mixed.frac.numerator}}{${overrideDenom ?? mixed.frac.denominator}}`;
      if ((overrideNum ?? mixed.frac.numerator) === 0)
        return `${sign}${overrideMixed ?? mixed.whole}`;
      return `${sign}${overrideMixed ?? mixed.whole} ${Math.abs(
        overrideNum ?? mixed.frac.numerator
      )}/${overrideDenom ?? mixed.frac.denominator}`;
    }
    if (this.denominator === 1) {
      return `${sign}${Math.abs(num)}`;
    }
    // if (useLatex)
    //   return `${sign}\\frac{${overrideNum ?? this.numerator}}{${overrideDenom ?? this.denominator}}`;
    return `${sign}${Math.abs(num)}/${overrideDenom ?? this.denominator}`;
  }

  // toString() {
  //   const sign = this.numerator < 0 ? "-" : "";
  //   if (this.isMixed()) {
  //     const mixed = this.getMixed();
  //     if (mixed.frac.numerator === 0)
  //       return `${sign}${mixed.whole}`;
  //     return `${sign}${mixed.whole} ${mixed.frac.numerator}/${mixed.frac.denominator}`;
  //   }
  //   return `${sign}${this.numerator}/${this.denominator}`;
  // }

  getValue() {
    return this.numerator / this.denominator;
  }

  getAnswerArr() {
    const arr = [this.formatted({ useImproper: true })];
    if (this.isMixed()) {
      arr.push(this.formatted());
    }
    if (this.getValue().toString().length < 8)
      arr.push(this.getValue().toString());
    return arr.filter((x, i) => arr.indexOf(x) === i);
  }
}

export class QuestionGeneratorList {
  rng: RNG;
  randoms: {
    random: () => number;
    randomInt: (min: number, max: number) => number;
  };
  questionGens: { [key: string]: QuestionGenerator };
  tiers: string[][];
  constructor(rng: RNG) {
    this.rng = rng;
    this.randoms = {
      random: rng.random.bind(rng),
      randomInt: rng.randomInt.bind(rng),
    };
    const { random, randomInt } = this.randoms;
    this.questionGens = {
      add: {
        name: "Addition",
        description: "Add two four-digit numbers",
        weight: 20,
        tier: 0,
        func: (min = 10, max = 9999) => {
          const a = randomInt(min, max);
          const b = randomInt(min, max);
          return { ans: a + b, str: `\`${a} + ${b} = \`` };
        },
      },
      sub: {
        name: "Subtraction",
        description: "Subtract two four-digit numbers",
        weight: 20,
        tier: 0,
        func: (min = 10, max = 9999) => {
          let a: number;
          let b = randomInt(min, max);
          do {
            a = randomInt(min, max);
          } while (a == b);
          if (a < b) {
            [a, b] = [b, a];
          }
          return { ans: a - b, str: `\`${a} - ${b} = \`` };
        },
      },
      mult: {
        name: "Multiplication",
        description: "3-digit by 2-digit FOIL",
        weight: 30,
        tier: 1,
        func: (min = 10, maxA = 599, maxB = 79) => {
          const a = randomInt(min, maxA);
          const b = randomInt(min, maxB);
          return { ans: a * b, str: `\`${a} xx ${b} = \`` };
        },
      },
      div: {
        name: "Division",
        description: "Divide two numbers",
        weight: 10,
        tier: 1,
        func: (min = 5, maxAns = 100, maxDiv = 40) => {
          // a isdividend, b isdivisor
          // a's randomInt() isthe answer
          const b = randomInt(min, maxDiv);
          const a = b * randomInt(min, maxAns);
          return { ans: a / b, str: `\`${a} -: ${b} = \`` };
        },
      },
      sqrt: {
        name: "Square Root Estimation",
        description:
          "Estimate the square root of a number. Remove 2 digits from the back of the number until you can estimate (2-3 digits), then multiply by 10 per 2 digits removed.",
        weight: 20,
        tier: 1,
        func: () => {
          const d = randomInt(4, 8);
          const a = Math.round(random() * Math.pow(10, d));
          return { ans: Math.sqrt(a), str: `*\`sqrt(${a}) = \``, guess: true };
        },
      },
      cbrt: {
        name: "Cube Root Estimation",
        description:
          "Estimate the cube root of a number. Remove 3 digits from the back of the number until you can estimate (3-4 digits), then multiply by 10 per 3 digits removed.",
        weight: 20,
        tier: 2,
        func: () => {
          const d = randomInt(4, 9);
          const a = Math.round(random() * Math.pow(10, d));
          return {
            ans: Math.cbrt(a),
            str: `*\`root(3)(${a}) = \``,
            guess: true,
          };
        },
      },
      rdec: {
        name: "Repeating Decimal",
        description:
          "Convert a repeating decimal to a fraction. Let a be the constant part and b be the repeating part. The denominator is 9 for each digit in b followed by 0 for each digit in a." +
          " The numerator is the number formed by concatenating a and b, minus a. Be sure to simplify at the end.",
        weight: 20,
        tier: 1,
        func: () => {
          const d = randomInt(0, 1);
          const bLen = randomInt(1, 2);
          const dMult = Math.pow(10, d);
          const b = (Math.pow(10, bLen) - 1) * dMult;
          let a = randomInt(1, b - 1);
          let frac = new Fraction(a, b);
          if (
            frac.denominator % 5 === 0 &&
            frac.denominator % 2 === 0 &&
            frac.denominator % 3 != 0 &&
            frac.denominator % 11 != 0
          ) {
            a = randomInt(1, b - 1);
            frac = new Fraction(a, b);
          }
          const rep = `${a % (b / dMult)}`.padStart(bLen, "0");
          const pre = Math.floor((a / b) * dMult);
          const str = `\`.${d > 0 ? pre : ""}${rep}${rep}${rep}... = \``;
          return {
            ans: 0,
            str: str,
            ansStr: new Fraction(a, b).formatted(),
          };
        },
      },
      sq: {
        name: "Memorized Squares",
        description: "Squares of numbers 2-60",
        weight: 10,
        tier: 0,
        func: () => {
          const a = randomInt(2, 60);
          return { ans: a * a, str: `\`${a}^2 = \`` };
        },
      },
      cb: {
        name: "Memorized Cubes",
        description: "Cubes of numbers 2-20",
        weight: 10,
        tier: 1,
        func: () => {
          const a = randomInt(2, 20);
          return { ans: a * a * a, str: `\`${a}^3 = \`` };
        },
      },
      sqadd1: {
        name: "Sum of Squares 1",
        description:
          "Sum of squares case 1: Let `a^2 + b^2 = x` where a's tens digit + b's ones digit = 10, and a's ones digit = b's tens digit + 1. `x =` sum of squares of a's digits.",
        weight: 10,
        tier: 1,
        func: () => {
          // if (random() < 0.5) {
          let a = randomInt(2, 9);
          let b = randomInt(1, 9);
          let d;
          const nums = [b, a, a - 1, 10 - b];
          if (random() < 0.5) {
            d = nums[0];
            nums[0] = nums[3];
            nums[3] = d;
          }
          if (random() < 0.5) {
            d = nums[0];
            nums[0] = nums[2];
            nums[2] = d;
            d = nums[1];
            nums[1] = nums[3];
            nums[3] = d;
          }
          a = nums[0] * 10 + nums[1];
          b = nums[2] * 10 + nums[3];
          return { ans: a * a + b * b, str: `\`${a}^2 + ${b}^2 = \`` };
          // }
          // let a = randomInt(4, 13) * 5;
          // let b = Math.sign(random() - 0.5) + a;
          // if (random() < 0.5) {
          //   d = a;
          //   a = b;
          //   b = d;
          // }
          // return { ans: a * a + b * b, str: `\`${a}^2 + ${b}^2\`` };
        },
      },
      // TODO: 84^2 + 24^2 trick
      sqadd2: {
        name: "Sum of Squares 2",
        description:
          "Sum of squares case 2: Let `a^2 + b^2 = x`, the midpoint between a and b is `m = (a + b) / 2` and the distance between a and b is `d = (b - a) / 2`. `x = 2(m^2 + d^2)`.",
        weight: 10,
        tier: 1,
        func: () => {
          // if (random() < 0.5) {
          let m = randomInt(40, 60);
          let d = randomInt(10, 30);
          if (random() < 0.5) {
            m = Math.round(m / 10) * 10;
          } else {
            d = Math.round(d / 10) * 10;
          }
          const a = m - d;
          const b = m + d;
          return { ans: a * a + b * b, str: `\`${a}^2 + ${b}^2 = \`` };
          // }
          // let a = randomInt(4, 13) * 5;
          // let b = Math.sign(random() - 0.5) + a;
          // if (random() < 0.5) {
          //   d = a;
          //   a = b;
          //   b = d;
          // }
          // return { ans: a * a + b * b, str: `\`${a}^2 + ${b}^2\`` };
        },
      },
      fracadd: {
        name: "Fraction Addition",
        description: "Add two fractions, answer with mixed or proper fraction.",
        weight: 20,
        tier: 1,
        func: () => {
          const b = randomInt(2, 9);
          let a = 0;
          do {
            a = randomInt(1, 4 * b - 1);
          } while (a % b === 0);
          const d = randomInt(2, 7);
          let c = 0;
          do {
            c = randomInt(1, 4 * d - 1);
          } while (c % d === 0);
          const frac1 = new Fraction(a, b);
          const frac2 = new Fraction(c, d);
          const denom = frac1.denominator * frac2.denominator;
          const improper =
            frac1.numerator * frac2.denominator +
            frac2.numerator * frac1.denominator;
          const ansFrac = new Fraction(improper, denom);
          if (improper % denom === 0) {
            return this.questionGens.fracadd.func();
          }
          return {
            ans: 0,
            str: `\`${frac1.formatted()} + ${frac2.formatted()}\` (${
              ansFrac.isMixed() ? "mixed" : "proper"
            })`,
            ansStr: ansFrac.formatted(),
          };
        },
      },
      fracadd2: {
        name: "a/b + b/a",
        description:
          "Reciprocal fraction addition. Answer is `2 + (a - b)^2 / (ab)`. If `a` and `b` are linear functions with the form `x + c`, then the result is `2 B/C` where `B` is `(b - a)^2`.",
        weight: 8,
        tier: 1,
        func: () => {
          if (random() < .5) {
            // The 2B/C trick
            const dist = randomInt(3, 20);
            const mid = randomInt(-5, 5);
            const a = mid - Math.floor(dist / 2);
            const b = mid + Math.ceil(dist / 2);
            const str1 = `x ${a > 0 ? "+" : "-"} ${Math.abs(a)}`;
            const str2 = `x ${b > 0 ? "+" : "-"} ${Math.abs(b)}`;
            return {
              ans: (b - a) * (b - a),
              str: `Let \`(${str1})/(${str2}) + (${str2})/(${str1}) = 2 B/C\`. Find \`B\`.`,
            }
          }
          // a/b + b/a
          const a = randomInt(5, 15);
          const b = Math.sign(random() - 0.5) * randomInt(1, 3) + a;
          const frac1 = new Fraction(a, b);
          const frac2 = new Fraction(b, a);
          const num = Math.pow(frac1.denominator - frac1.numerator, 2);
          const denom = frac1.denominator * frac2.denominator;
          const ansFrac = new Fraction(2 * denom + num, denom);
          return {
            ans: 0,
            str: `\`${frac1.formatted({
              useImproper: true,
            })} + ${frac2.formatted({ useImproper: true })}\` (mixed)`,
            ansStr: ansFrac.formatted(),
          };
        },
      },
      fracadd3: {
        name: "Sum of Telescoping Fractions",
        description:
          "Sum of fractions with telescoping denominator. Each term can be represented as `1/(a xx (a + n))` where n is the constant interval. Numerator is number of terms, denominator is product of first term's `a` with the last term's `a + n`. Be sure to simplifiy.",
        weight: 10,
        tier: 2,
        func: () => {
          // reciprocal of arithmetic series
          const a = randomInt(2, 5);
          const diff = randomInt(1, 3);
          const n = randomInt(3, 5);
          const arr = Array(n)
            .fill(0)
            .map((_, i) => (a + i * diff) * (a + (i + 1) * diff));
          const denom = a * (a + n * diff);
          const ansFrac = new Fraction(n, denom);
          return {
            ans: 0,
            str: `\`${arr.map((x) => `1/${x}`).join(" + ")} = \``,
            ansStr: ansFrac.formatted(),
          };
        },
      },
      fracadd4: {
        name: "Geometric Series",
        description:
          "Sum of geometric series. Answer is `a_1/(1 - r)` where `a_1` is the first term and `r` is the common ratio.",
        weight: 10,
        tier: 2,
        func: () => {
          // geometric series
          const a = randomInt(2, 5);
          const rDen = randomInt(2, 6);
          const rNum = randomInt(1, rDen - 1) * Math.sign(random() - 0.3);
          const ansNum = a * rDen;
          const ansDen = rDen - rNum;
          const ans = new Fraction(ansNum, ansDen);
          const arr = Array(5)
            .fill(0)
            .map((_, i) =>
              new Fraction(a * Math.pow(rNum, i), Math.pow(rDen, i)).formatted()
            );
          return {
            ans: 0,
            str: `\`${joinAdd(arr)} + ... = \``,
            ansStr: ans.formatted({ useImproper: true }),
          };
        },
      },
      ngonal: {
        name: "Polygonal Numbers",
        description: "Find the xth ngonal number where n corresponds to the sides of the shape. Formula is `x((n - 2)x - (n - 4)) / 2`.",
        weight: 20,
        tier: 1,
        func: () => {
          let gon = randomInt(3, 9);
          if (gon >= 4) gon++;
          const n = randomInt(2, 15 - gon);
          return {
            ans: (n * ((gon - 2) * n - (gon - 4))) / 2,
            str: `Find the ${getNumberRankStr(n)} ${polygonStrs[gon]} number`,
          };
        },
      },
      modexp: {
        name: "Modular Exponentiation",
        description: "Use Fermat's Little Theorem when possible. Questions contain some that can't be solved normally, so practice brute force.",
        weight: 10,
        tier: 3,
        func: () => {
          const base = randomInt(10, 150);
          const mod = randomInt(3, 25);
          let exp = randomInt(3, 20);
          if (random() < 0.4) {
            exp = mod + randomInt(-1, 2);
          }

          return {
            ans: binaryExp(base, exp, mod),
            str: `Find the remainder of \`${base}^${exp} -: ${mod}\``,
          };
        },
      },
      mod: {
        name: "Modular Arithmetic",
        description: "Perform arithmetic operators but with modulo. First, modulo every number, then modulo after every operation performed.",
        weight: 30,
        tier: 1,
        func: () => {
          if (random() < 0.5) {
            const a = randomInt(5, 80);
            const b = randomInt(3, 25);
            const c = randomInt(3, 25);
            const d = randomInt(5, 40);
            const mod = randomInt(3, 8);
            return {
              ans: (a + b * c - d) % mod,
              str: `Find the remainder of \`(${a} + ${b} xx ${c} - ${d}) -: ${mod}\``,
            };
          }
          const a = randomInt(1000, 99999);
          const mod = randomInt(3, 12);
          return {
            ans: a % mod,
            str: `Find the remainder of \`${a} -: ${mod}\``,
          };
        },
      },
      pow: {
        name: "Exponent Algebra",
        description: "Change every term to be in the smallest base. Treat the expression as sum/difference of the exponents, then apply the exponent at the end if needed.",
        weight: 20,
        tier: 2,
        func: () => {
          const base = randomInt(2, 8);
          const aPow = randomInt(1, 3);
          const cPow = randomInt(1, 2);
          let a = 0;
          do {
            a = randomInt(-3, Math.floor(8 / aPow));
          } while (a == 0);
          let b = 0;
          do {
            b = randomInt(-4, 8);
          } while (b == 0);
          let c = 0;
          do {
            c = randomInt(-3, Math.floor(8 / cPow));
          } while (c == 0);
          const ans = aPow * a - b + cPow * c;
          if (ans >= -3 && ans <= 3 && random() < 0.9)
            return {
              ans: 0,
              str: `\`${Math.pow(
                base,
                aPow
              )}^${a} -: ${base}^${b} xx ${Math.pow(base, cPow)}^${c} = \``,
              ansStr:
                ans >= 0
                  ? Math.pow(base, ans).toString()
                  : `1/${Math.pow(base, -ans)}`,
            };
          return {
            ans: ans,
            str: `Let \`${Math.pow(
              base,
              aPow
            )}^${a} -: ${base}^${b} xx ${Math.pow(
              base,
              cPow
            )}^${c} = ${base}^k\`. Find k`,
          };
        },
      },
      fracmult: {
        name: "Fraction Multiplication",
        description: "Multiply two fractions, answer in any form",
        weight: 12,
        tier: 0,
        func: () => {
          // generic frac mult
          const d1 = randomInt(2, 12);
          const d2 = randomInt(2, 12);
          const n1 = randomInt(1, d1 - 1);
          const n2 = randomInt(1, d2 - 1);
          const ansFrac = new Fraction(n1 * n2, d1 * d2);
          return {
            ans: 0,
            str: `\`${new Fraction(n1, d1).formatted()} xx ${new Fraction(
              n2,
              d2
            ).formatted()} = \``,
            ansArr: ansFrac.getAnswerArr(),
          };
        },
      },
      fracmult2: {
        name: "a * b / c",
        description: "Multiplication of numbers close to each other. Answer is `a + b - c + ((c - a)(c - b)) / c`.",
        weight: 10,
        tier: 2,
        func: () => {
          // a * b/c where a and b are close to c
          const c = randomInt(13, 25);
          let b = c;
          do {
            b = c + randomInt(1, 4) * Math.sign(random() - 0.6666);
          } while (gcd(b, c) > 1);
          let a = c;
          do {
            a = c + randomInt(1, 7) * Math.sign(random() - 0.6666);
          } while (gcd(a, c) > 1);
          let numer = (c - a) * (c - b);
          const val = a + b - c + Math.floor(numer / c);
          numer = ((numer % c) + c) % c;
          return {
            ans: 0,
            str: `\`${a} xx ${new Fraction(b, c).formatted({
              useImproper: true,
            })}\` (mixed)`,
            ansStr: `${val} ${numer}/${c}`,
          };
        }
      },
      fracmult3: {
        name: "Fraction Multiplication with m and n",
        description: "First estimate the value of n on the lower end. Then convert n's fraction to improper, divide any gcd of the resulting numerator and the product, and you will get m.",
        weight: 8,
        tier: 2,
        func: () => {
          // x y/m + n z/a = b, find m and n
          const c = randomInt(10, 32);
          const bDen = randomInt(3, 12);
          let bNum = 0;
          do {
            bNum = randomInt(bDen * 2, Math.round(Math.sqrt(c) * bDen));
          } while ((c * bDen) % bNum == 0);
          const frac2 = new Fraction(bNum, bDen);
          const frac1 = new Fraction(c * frac2.denominator, frac2.numerator);
          const m = frac1.denominator,
            n = frac2.getWhole();
          const str = `\`${frac1.formatted({
            overrideDenom: "m",
          })} xx ${frac2.formatted({ overrideMixed: "n" })} = ${c}\`. `;
          switch (randomInt(0, 3)) {
            case 0:
              return {
                ans: m + n,
                str: str + "`m + n = `",
              };
            case 1:
              return {
                ans: m - n,
                str: str + "`m - n = `",
              };
            case 2:
              return {
                ans: n - m,
                str: str + "`n - m = `",
              };
            default:
              return { ans: m * n, str: str + "`mn = `" };
          }
        }
      },
      fracmult4: {
        name: "Mixed Number FOIL",
        description: "FOIL with mixed numbers. Treat each mixed number as a whole number plus a fraction, then FOIL as if the whole number part is the tens digit and the fraction is the ones digit.",
        weight: 10,
        tier: 1,
        func: () => {
          // foil where a b/c * d e/f and a % f == 0 and d % c == 0
          const d1 = randomInt(2, 12);
          const d2 = randomInt(2, 12);
          const n1 = Math.max(randomInt(-2, Math.min(5, d1 - 1)), 1);
          const n2 = Math.max(randomInt(-2, Math.min(5, d2 - 1)), 1);
          const frac1 = new Fraction(n1, d1);
          const frac2 = new Fraction(n2, d2);
          const a = Math.max(randomInt(-2, 3), 1) * frac2.denominator;
          const b = Math.max(randomInt(-2, 3), 1) * frac1.denominator;
          const ansFrac = new Fraction(
            frac1.numerator * frac2.numerator,
            frac1.denominator * frac2.denominator
          );
          const mixed1 = new Fraction(
            a * frac1.denominator + frac1.numerator,
            frac1.denominator
          );
          const mixed2 = new Fraction(
            b * frac2.denominator + frac2.numerator,
            frac2.denominator
          );
          const whole =
            a * b +
            (a / frac2.denominator) * frac2.numerator +
            (b / frac1.denominator) * frac1.numerator;
          return {
            ans: 0,
            str: `\`${mixed1.formatted()} xx ${mixed2.formatted()}\` (mixed)`,
            ansStr: `${new Fraction(
              whole * ansFrac.denominator + ansFrac.numerator,
              ansFrac.denominator
            ).formatted()}`,
          };
        }
      },
      complex: {
        name: "Complex Numbers",
        description: "Multiply two complex numbers. Use FOIL to figure out the answer's complex and real parts.",
        weight: 20,
        tier: 2,
        func: () => {
          const a = randomInt(1, 9);
          const b = randomInt(1, 9);
          const c = randomInt(1, 9);
          const d = randomInt(1, 9);
          const neg = random() < 0.5;
          const str = `\`(${a} ${
            neg ? "-" : "+"
          } ${b}i)(${c} + ${d}i) = a + bi\`. `;
          if (a + b + c + d < 16 && random() < 0.5) {
            return {
              ans:
                (a * c - b * d * (neg ? -1 : 1)) *
                (a * d + b * c * (neg ? -1 : 1)),
              str: str + "`ab = `",
            };
          }
          switch (randomInt(0, 2)) {
            case 0:
              return {
                ans: a * c - a * d - (b * c + b * d) * (neg ? -1 : 1),
                str: str + "`a - b = `",
              };
            case 1:
              return {
                ans: a * d - a * c + (b * c + b * d) * (neg ? -1 : 1),
                str: str + "`b - a = `",
              };
            default:
              return {
                ans: a * c + a * d + (b * c - b * d) * (neg ? -1 : 1),
                str: str + "`a + b = `",
              };
          }
        },
      },
      estmix: {
        name: "Mixed Estimation",
        description: "Estimate the sum of two numbers with a product. Round the multiplication part first, find the product, then add afterwards.",
        weight: 20,
        tier: 1,
        func: () => {
          const a = randomInt(1000, 99999);
          const c = randomInt(10, 40);
          const b = randomInt(100, a / c * 2);
          return {
            ans: a + b * c,
            str: `*\`${a} + ${b} xx ${c} = \``,
            guess: true,
          };
        },
      },
      estdiv: {
        name: "Division Estimation",
        description: "Estimate division. Usually round to closest numbers, divide, then increase/decrease a bit depending on which way you round.",
        weight: 10,
        tier: 1,
        func: () => {
          const a = randomInt(3000, 80000);
          const b = randomInt(10, 80);
          return { ans: a / b, str: `*\`${a} -: ${b} = \``, guess: true };
        },
      },
      fibsum: {
        name: "Fibonacci Sum",
        description: "Sum of a Fibonacci Series. Let `F(n)` be the last Fibonacci number in this series starting with `F(1)`. The answer is `F(n + 2) - F(2)` which is equal to `2F(n) + F(n - 1) - F(2)`.",
        weight: 20,
        tier: 2,
        func: () => {
          const vals = [randomInt(1, 10), randomInt(1, 6)];
          const n = randomInt(7, 12);
          for (let i = 2; i < n; i++) {
            vals.push(vals[i - 1] + vals[i - 2]);
          }
          if (random() < 0.4) {
            // frac fib
            const frac = Math.pow(2, randomInt(1, 3));
            const fracs = vals.map((v, _) => new Fraction(v, frac));
            let str = `\``;
            for (let i = 0; i < 5; i++) {
              str +=
                random() < 0.33
                  ? random() < 0.5
                    ? `${fracs[i].formatted({ useImproper: true })} + `
                    : `${fracs[i].getValue()} + `
                  : `${fracs[i].formatted()} + `;
            }
            str += `... + ${fracs[fracs.length - 2].formatted()} + ${fracs[
              fracs.length - 1
            ].formatted()} = \``;
            const ansFrac = new Fraction(
              (fracs[fracs.length - 1].getValue() * 2 +
                fracs[fracs.length - 2].getValue() -
                fracs[1].getValue()) *
                frac,
              frac
            );
            return {
              ans: 0,
              str: str,
              ansArr: ansFrac.getAnswerArr(),
            };
          }
          return {
            ans: vals[vals.length - 1] * 2 + vals[vals.length - 2] - vals[1],
            str: `\`${vals[0]} + ${vals[1]} + ${vals[2]} + ${vals[3]} + ${
              vals[4]
            } + ... + ${vals[vals.length - 2]} + ${vals[vals.length - 1]} = \``,
          };
        },
      },
      trirecip: {
        name: "Reciprocal Triangular Numbers",
        description: "Sum of the reciprocals of the first n triangular numbers. Answer is `1 + (n - 1) / (n + 1)`, subtract 1 if the series doesn't start with 1.",
        weight: 10,
        tier: 1,
        func: () => {
          const n = randomInt(3, 10);
          const num = n - 1;
          const den = n + 1;
          const ansFrac = new Fraction(num, den);
          const arr = Array(n - 1)
            .fill(0)
            .map((_, i) =>
              new Fraction(1, ((i + 2) * (i + 3)) / 2).formatted()
            );
          let str = arr.slice(0, Math.min(arr.length - 1, 4)).join(" + ");
          if (arr.length > 5) str += " + ...";
          str += " + " + arr[arr.length - 1];
          str += " = ";
          if (random() < 0.3) {
            return {
              ans: 0,
              str: `\`${str}\``,
              ansArr: ansFrac.getAnswerArr(),
            };
          }
          if (random() < 0.5) {
            return {
              ans: 0,
              str: `\`1 + ${str}\``,
              ansArr: new Fraction(num + den, den).getAnswerArr(),
            };
          }
          return {
            ans: 0,
            str: `The sum of the reciprocals of the first \`${n}\` triangular numbers is`,
            ansArr: new Fraction(num + den, den).getAnswerArr(),
          };
        },
      },
      binomexp: {
        name: "Binomial Expansion",
        description: "Find the coefficient of a term in a binomial expansion. If in the form `(ax + by)^c` and the term is `x^i y^j`, first find `a^i b^j`. " +
          "Then multiply the result with the corresponding Pascal's Triangle term, which can be calculated using `(n!)/(k!(n - k)!)` where `n` is the total exponent and `k` is either the x or y exponent (doesn't matter).",
        weight: 20,
        tier: 3,
        func: () => {
          const exp = randomInt(3, 6);
          const a = randomInt(1, 8 - exp);
          const b = randomInt(1, 8 - exp) * Math.sign(random() - 0.5);
          const str = `\`(${a > 1 ? a : ""}x ${b > 0 ? "+" : "-"} ${
            Math.abs(b) > 1 ? Math.abs(b) : ""
          }y)^${exp}\``;
          const term = randomInt(2, exp);
          let coef = Math.pow(a, exp - term + 1) * Math.pow(b, term - 1);
          for (let i = exp; i > 1; i--) {
            coef *= i;
          }
          for (let i = 2; i < term; i++) {
            coef /= i;
          }
          for (let i = 2; i <= exp - term + 1; i++) {
            coef /= i;
          }
          switch (randomInt(0, 2)) {
            case 0:
              return {
                ans: coef,
                str: `The coefficient of the ${getNumberRankStr(
                  term
                )} term of ${str} is`,
              };
            case 1:
              return {
                ans: coef,
                str: `The coefficient of the \`x^${exp - term + 1} y^${
                  term - 1
                }\` term of ${str} is`,
              };
            default:
              return {
                ans: coef + exp,
                str: `If the ${getNumberRankStr(
                  term
                )} term in the expansion of ${str} is \`cx^ay^b\`, then \`a + b + c = \``,
              };
          }
        },
      },
      binomsum: {
        name: "Binomial Sum",
        description: "Sum of the coefficients of a binomial expansion. If in the form `(ax + by)^c`, the answer is `(a + b)^c`.",
        weight: 8,
        tier: 2,
        func: () => {
          const exp = randomInt(3, 6);
          const a = randomInt(1, 8 - exp);
          const b = randomInt(1, 8 - exp) * Math.sign(random() - 0.5);
          const str = `\`(${a > 1 ? a : ""}x ${b > 0 ? "+" : "-"} ${
            Math.abs(b) > 1 ? Math.abs(b) : ""
          }y)^${exp}\``;
          return {
            ans: Math.pow(a + b, exp),
            str: "The sum of the coefficients of " + str + " is",
          };
        }
      },
      relprime: {
        name: "Relatively Prime",
        description: "Find the number of integers less than a number that are relatively prime to it. Use Euler's Totient Function to find the answer. If there is a lower bound, manually subtract from the result.",
        weight: 10,
        tier: 1,
        func: () => {
          let a = 0;
          do {
            a = randomInt(8, 50);
          } while (primes.includes(a));
          const arr: number[] = [];
          let temp = a;
          for (let i = 2; i <= temp; i++) {
            while (temp % i == 0) {
              if (!arr.includes(i)) arr.push(i);
              temp /= i;
            }
          }
          let ans = arr.reduce((acc, val) => (acc * (val - 1)) / val, a);
          const start = Math.max(randomInt(-2, 5), 1);
          for (let i = 1; i < start; i++) {
            if (gcd(i, a) == 1) ans--;
          }
          return {
            ans: ans,
            str:
              start == 1
                ? `Find the number of integers less than \`${a}\` that are relatively prime to \`${a}\``
                : `Find the number of integers between \`${
                    start - 1
                  }\` and \`${a}\` that are relatively prime to \`${a}\``,
          };
        },
      },
      posfact: {
        name: "Positive Integral Divisors",
        description: "Number of positive integral divisors of a number. Find the prime factorization written as the product `\\prod_i p_i^(a_i)` where `p_i` is the prime and `a_i` is the exponent of every prime factor of a number. " +
          "The answer is product of the exponents + 1 or `\\prod_i a_i + 1`.",
        weight: 10,
        tier: 1,
        func: () => {
          let a = 0;
          do {
            a = randomInt(8, 50);
          } while (primes.includes(a));
          const arr: number[] = [];
          let temp = a;
          let ans = 1;
          for (let i = 2; i <= temp; i++) {
            let count = 1;
            while (temp % i == 0) {
              if (!arr.includes(i)) arr.push(i);
              temp /= i;
              count++;
            }
            ans *= count;
          }
          //if (random() < .4) {
          //  return { ans: arr.length, str: `Find the number of positive prime divisors of \`${a}\`` };
          //}
          return {
            ans: ans,
            str: `Find the number of positive integral divisors of \`${a}\``,
          };
        },
      },
      base: {
        name: "Base Conversion",
        description: "To convert from base 10 to another base, divide the number by the base and take the remainder (this will fill in answer right to left). Repeat the process until the quotient is 0. " +
          "To convert from another base to base 10, multiply each digit by the base raised to the power of its position. For speed, go from left to right, multiplying the running answer by the base and adding the next digit.",
        weight: 10,
        tier: 3,
        func: () => {
          const base = randomInt(2, 9);
          const a = randomInt(20, 250);
          const conv = parseInt(a.toString(base));
          if (random() < 0.5) {
            return {
              ans: conv,
              str: `Convert \`${a}_10\` to base \`${base}\``,
            };
          }
          return { ans: a, str: `Convert \`${conv}_${base}\` to base \`10\`` };
        },
      },
      basearith: {
        name: "Base Arithmetic",
        description: "Arithmetic operations in another base. For addition/subtraction, carry and regroup with the new base instead of 10. For multiplication, convert to the base after every FOIL step. " +
          "For division, first convert the divisor to base 10. Then keep converting part of the dividend and try dividing. Or you can convert both to base 10 and divide.",
        weight: 30,
        tier: 3,
        func: () => {
          const mode = randomInt(1, 4);
          if (mode == 1) {
            const a = randomInt(10, 250);
            const b = randomInt(10, 250);
            const base = randomInt(4, 9);
            return {
              ans: parseInt((a + b).toString(base)),
              str: `\`${a.toString(base)}_${base}+${b.toString(
                base
              )}_${base} = \``,
            };
          } else if (mode == 2) {
            const a = randomInt(10, 250);
            const b = randomInt(10, 250);
            const base = randomInt(4, 9);
            return {
              ans: parseInt((a - b).toString(base)),
              str: `\`${a.toString(base)}_${base} - ${b.toString(
                base
              )}_${base} = \``,
            };
          } else if (mode == 3) {
            const a = randomInt(10, 80);
            const b = randomInt(4, 25);
            const base = randomInt(4, 9);
            return {
              ans: parseInt((a * b).toString(base)),
              str: `\`${a.toString(base)}_${base} xx ${b.toString(
                base
              )}_${base} = \``,
            };
          }
          const b = randomInt(2, 9);
          const a = b * randomInt(5, 25);
          const base = randomInt(4, 9);
          return {
            ans: parseInt((a / b).toString(base)),
            str: `\`${a.toString(base)}_${base} -: ${b.toString(
              base
            )}_${base} = \``,
          };
        },
      },
      inverse: {
        name: "Inverse Functions",
        description: "Solve for inverse equations. Keep track of different coefficients and values in your head and do algebra.",
        weight: 10,
        tier: 3,
        func: () => {
          const a = randomInt(2, 9);
          const b = randomInt(2, 9) * Math.sign(random() - 0.3);
          const c = randomInt(2, 6);
          const d = randomInt(2, 6) * Math.sign(random() - 0.3);
          if (random() < 0.5) {
            // One var inverse
            const e = randomInt(2, 6) * Math.sign(random() - 0.3);
            return {
              ans: 0,
              str: `If \`f(x) = (${a}x ${b > 0 ? `+` : `-`} ${Math.abs(
                b
              )}) / ${c} ${d > 0 ? `+` : `-`} ${Math.abs(
                d
              )}\`, what is the value of \`f^-1(${e})\`?`,
              ansArr: new Fraction(c * (e - d) - b, a).getAnswerArr(),
            };
          }
          // Normal linear over linear inverse
          let e = 1;
          do {
            e = randomInt(1, 4) * Math.sign(random() - 0.5);
          } while (e * c == a);
          return {
            ans: 0,
            str: `If \`f(x) = (${a}x ${b > 0 ? `+` : `-`} ${Math.abs(
              b
            )}) / (${c}x ${d > 0 ? `+` : `-`} ${Math.abs(
              d
            )})\`, what is the value of \`f^-1(${e})\`?`,
            ansArr: new Fraction(b - e * d, e * c - a).getAnswerArr(),
          };
        },
      },
      inverseline: {
        name: "Inverse Linear Functions",
        description: "Find the inverse of a linear function. If original function is `f(x) = ax + b`, the inverse function has slope `1/a` and y-intercept `-b/a`.",
        weight: 10,
        tier: 3,
        func: () => {
          const aDen = randomInt(4, 9);
          let aNum = 0;
          do {
            aNum = randomInt(2, aDen - 1);
          } while (gcd(aNum, aDen) > 1);
          const bDen = randomInt(4, 9);
          let bNum = 0;
          do {
            bNum = randomInt(2, bDen - 1);
          } while (gcd(bNum, bDen) > 1);
          const a = new Fraction(aNum, aDen);
          const b = new Fraction(bNum, bDen);
          const str = `Let \`f(x) = ${a.formatted()}x ${b.getValue() > 0 ? "+" : "-"} ${new Fraction(Math.abs(bNum), bDen).formatted()}\`. If \`f^(-1)(x) = ax + b\`, then `;
          if (random() < .5) {
            return {
              ans: 0,
              str: str + "`a = `",
              ansArr: new Fraction(aDen, aNum).getAnswerArr(),
            }
          }
          return {
            ans: 0,
            str: str + "`b = `",
            ansArr: new Fraction(-bNum * aDen, bDen * aNum).getAnswerArr(),
          }
        }
      },
      // date: {
      //   weight: 10,
      //   func: () => {
      //     const a = new Date(2024, randomInt(0, 6), randomInt(1, 28));
      //     const b = new Date(2024, a.getMonth() + randomInt(1, 4), randomInt(1, 28));
      //     let diff = Math.round((b.getTime() - a.getTime()) / (1000 * 60 * 60 * 24));
      //     const aBegin = random() < .5;
      //     const bBegin = random() < .5;
      //     if (aBegin)
      //       diff++;
      //     if (bBegin)
      //       diff--;
      //     return {
      //       ans: diff,
      //       str: `How many days are between ${aBegin ? "the beginning of " : "the end of "}${months[a.getMonth()]} \`${a.getDate()}, ${a.getFullYear()}\` and ${bBegin ? "the beginning of " : "the end of "}${months[b.getMonth()]} \`${b.getDate()}, ${b.getFullYear()}\`?`
      //     };
      //   }
      // },
      set: {
        name: "Subsets",
        description: "Find the number of subsets of a set of `n` elements. For subsets of size `r`, the answer is `(n!) / (r!(n - r)!)`. For subsets containing `r` specific elements, the answer is `2^(n - r)`.",
        weight: 10,
        tier: 1,
        func: () => {
          const n = randomInt(5, 9);
          
          const arr: number[] = [];
          for (let i = 0; i < n; i++) {
            let letter = 0;
            do {
              letter = randomInt(0, 25);
            } while (arr.includes(letter));
            arr.push(letter);
          }
          if (random() < 0.5) {
            // Subsets containing r specific elements
            const r = randomInt(1, n - 2);
            const elements: number[] = [];
            for (let i = 0; i < r; i++) {
              let letter = 0;
              do {
                letter = arr[randomInt(0, n - 1)];
              } while (elements.includes(letter));
              elements.push(letter);
            }
            return {
              ans: Math.pow(2, n - r),
              str: `How many subsets containing the element${r > 1 ? `s \`[\`${elements
                .map((s) => String.fromCharCode(97 + s))
                .join(", ")}\`]\`` : ` ${String.fromCharCode(97 + elements[0])}`} are there in \`[\`${arr
                .map((s) => String.fromCharCode(97 + s))
                .join(", ")}\`]\`?`,
            }
          }
          // Subsets containing r elements
          const r = randomInt(2, n - 2);
          let ans = 1;
          for (let i = n; i > n - r; i--) {
            ans *= i;
          }
          for (let i = 2; i <= r; i++) {
            ans /= i;
          }
          return {
            ans: ans,
            str: `The set \`[\`${arr
              .map((s) => String.fromCharCode(97 + s))
              .join(", ")}\`]\` contains how many \`${r}\` element subsets?`,
          };
        },
      },
      lcm: {
        name: "LCM",
        description: "Least common multiple of two numbers. Use the formula `LCM(a, b) = (a * b) / (GCD(a, b))`.",
        weight: 10,
        tier: 0,
        func: () => {
          const c = randomInt(5, 20);
          const a = randomInt(2, 9) * c;
          let b = 0;
          do {
            b = randomInt(2, 9) * c;
          } while (b % a == 0 || a % b == 0);
          return {
            ans: (a * b) / gcd(a, b),
            str: `Find the LCM of \`${a}\` and \`${b}\``,
          };
        },
      },
      gcd: {
        name: "GCD",
        description: "Greatest common divisor of two numbers.",
        weight: 10,
        tier: 0,
        func: () => {
          const c = randomInt(5, 20);
          const a = randomInt(2, 9) * c;
          let b = 0;
          do {
            b = randomInt(2, 9) * c;
          } while (b == a);
          return {
            ans: gcd(a, b),
            str: `Find the GCD of \`${a}\` and \`${b}\``,
          };
        },
      },
      gcdlcm: {
        name: "GCD and LCM",
        description: "Given one value and their GCD and LCM, find the other. Use the formula `GCD(a, b) * LCM(a, b) = a * b`.",
        weight: 10,
        tier: 0,
        func: () => {
          const c = randomInt(2, 6);
          const a = randomInt(3, 12) * c;
          let b = 0;
          do {
            b = randomInt(3, 12) * c;
          } while (gcd(b, a) > c);
          const lcm = a * b / c;
          return {
            ans: b,
            str: `\`GCD(${a}, x) = ${c}\`, \`LCM(${a}, x) = ${lcm}\`, and \`x = \``
          }
        }
      },
      quadfact: {
        name: "Squared Quadratic",
        description: "Given a quadratic equation with 1 factor, find the output of the function with a given value. Factor the quadratic into `(ax + b)^2`, then plug in the value.",
        weight: 10,
        tier: 1,
        func: () => {
          const a = randomInt(1, 5);
          const b = randomInt(1, 5) * Math.sign(random() - 0.5);
          const c = randomInt(2, 9);
          return {
            ans: (a * c + b) * (a * c + b),
            str: `If \`f(x)=${a > 1 ? a * a : ""}x^2 ${b > 0 ? "+" : "-"} ${
              2 * a * Math.abs(b)
            }x + ${b * b}\`, find the value of \`f(${c})\``,
          };
        },
      },
      roundsqrt: {
        name: "Rounded Square Roots",
        description: "Find the sum of square roots rounded to nearest tenth. Have square roots from 2-10 memorized up to the hundreds digit.",
        weight: 10,
        tier: 1,
        func: () => {
          const nums = [2, 3, 5, 6, 7, 8, 10];
          const a = nums[randomInt(0, nums.length - 1)];
          const b = nums[randomInt(0, nums.length - 1)];
          return {
            ans: 0,
            str: `Find the value of \`sqrt(${a}) + sqrt(${b})\` rounded to the nearest tenth`,
            ansStr: (Math.sqrt(a) + Math.sqrt(b)).toFixed(1),
          };
        },
      },
      sumsqrt: {
        name: "Sum of Square Roots",
        description: "Sum of two square roots with a common factor. If you rewrite as `sqrt(a^2 xx c) + sqrt(b^2 xx c)`, the answer is `sqrt((a + b)^2 xx c)`.",
        weight: 10,
        tier: 3,
        func: () => {
          const a = randomInt(2, 7);
          const b = randomInt(2, 7);
          let c = 0;
          do {
            c = randomInt(2, 8);
          } while (c == 4);
          return {
            ans: (a + b) * (a + b) * c,
            str: `If \`sqrt(${a * a * c}) + sqrt(${
              b * b * c
            }) = sqrt(x)\`, then \`x = \``,
          };
        },
      },
      rootdata: {
        name: "Polynomial Roots",
        description: "Find the sum or product of roots of a polynomial. For quadratics `ax^2 + bx + c`, the sum of roots is `-b/a` and the product of roots is `c/a`. " +
          "For cubics `ax^3 + bx^2 + cx + d`, the sum of roots is `-b/a`, the sum of roots taken two at a time is `c/a`, the product of roots is `-d/a`, and the harmonic mean of roots is `-3d/c`.",
        weight: 40,
        tier: 2,
        func: () => {
          if (random() < 0.3) {
            const a = randomInt(2, 6);
            const b = randomInt(2, 12);
            const c = randomInt(2, 10);
            if (random() < 0.5) {
              return {
                ans: 0,
                str: `The product of the roots of \`${a}x^2 + ${b}x + ${c}\` is`,
                ansArr: new Fraction(c, a).getAnswerArr(),
              };
            }
            return {
              ans: 0,
              str: `The sum of the roots of \`${a}x^2 + ${b}x + ${c}\` is`,
              ansArr: new Fraction(-b, a).getAnswerArr(),
            };
          }
          const a = randomInt(2, 6);
          const b = randomInt(2, 12);
          const c = randomInt(2, 20);
          const d = randomInt(2, 15);
          const mode = randomInt(1, 4);
          if (mode == 1) {
            return {
              ans: 0,
              str: `The sum of the roots of \`${a}x^3 + ${b}x^2 + ${c}x + ${d} = 0\` is`,
              ansArr: new Fraction(-b, a).getAnswerArr(),
            };
          } else if (mode == 2) {
            return {
              ans: 0,
              str: `The product of the roots of \`${a}x^3 + ${b}x^2 + ${c}x + ${d} = 0\` is`,
              ansArr: new Fraction(-d, a).getAnswerArr(),
            };
          } else if (mode == 3) {
            return {
              ans: 0,
              str: `The sum of the roots taken two at a time of \`${a}x^3 + ${b}x^2 + ${c}x + ${d} = 0\` is`,
              ansArr: new Fraction(c, a).getAnswerArr(),
            };
          }
          return {
            ans: 0,
            str: `The harmonic mean of the roots of \`${a}x^3 + ${b}x^2 + ${c}x + ${d} = 0\` is`,
            ansArr: new Fraction(-3 * d, c).getAnswerArr(),
          };
        },
      },
      cuberules: {
        name: "Sum/Difference of Cubes",
        description: "Sum or difference of cubes. `a^3 + b^3 = (a + b)(a^2 - ab + b^2)` and `a^3 - b^3 = (a - b)(a^2 + ab + b^2)`.",
        weight: 30,
        tier: 2,
        func: () => {
          const mode = randomInt(1, 3);
          if (mode == 1) {
            const a = randomInt(1, 8) * Math.sign(random() - 0.5);
            const b = randomInt(1, 12) * Math.sign(random() - 0.5);
            if (random() < 0.5) {
              return {
                ans: (a * a - 3 * b) * a,
                str: `If \`x + y = ${a}\` and \`xy = ${b}\`, then \`x^3 + y^3 = \``,
              };
            }
            return {
              ans: (a * a + 3 * b) * a,
              str: `If \`x - y = ${a}\` and \`xy = ${b}\`, then \`x^3 - y^3 = \``,
            };
          }
          if (mode == 2) {
            const a = randomInt(1, 11);
            let b = 0;
            do {
              b = randomInt(1, 11) * Math.sign(random() - 0.5);
            } while (b == -a);
            return {
              ans: a * a - a * b + b * b,
              str: `\`(${a}^3 ${b > 0 ? "+" : "-"} ${Math.abs(b)}^3) -: (${a} ${
                b > 0 ? "+" : "-"
              } ${Math.abs(b)}) = \``,
            };
          }
          const a = randomInt(1, 8) * Math.sign(random() - 0.5);
          const b = randomInt(1, 8) * Math.sign(random() - 0.5);
          if (random() < 0.5) {
            return {
              ans: a * a * a + b * b * b,
              str: `If \`x = ${a}\` and \`y = ${b}\`, \`(x + y)(x^2 - xy + y^2) = \``,
            };
          }
          return {
            ans: a * a * a - b * b * b,
            str: `If \`x = ${a}\` and \`y = ${b}\`, \`(x - y)(x^2 + xy + y^2) = \``,
          };
        },
      },
      rootfrac: {
        name: "Fractional Roots",
        description: "Find the product of fractional roots. Treat each root as a fractional exponent and add the exponents together. Be sure to simplify.",
        weight: 20,
        tier: 3,
        func: () => {
          const b = randomInt(2, 4);
          let a = 0;
          do {
            a = randomInt(1, 4 * b - 1);
          } while (a % b == 0);
          const d = randomInt(2, 4);
          let c = 0;
          do {
            c = randomInt(1, 4 * d - 1);
          } while (c % d == 0);
          const frac1 = new Fraction(a, b);
          const frac2 = new Fraction(c, d);
          const denom = frac1.denominator * frac2.denominator;
          const improper =
            frac1.numerator * frac2.denominator +
            frac2.numerator * frac1.denominator;
          const ansFrac = new Fraction(improper, denom);
          const str = `If \`(root(${b})(a^${a}))(root(${d})(a^${c})) = root(n)(a^k)\`, then `;
          const mode = randomInt(1, 3);
          if (mode == 1) {
            return {
              ans: ansFrac.numerator,
              str: str + `\`k = \``,
            };
          }
          if (mode == 2) {
            return {
              ans: ansFrac.denominator,
              str: str + `\`n = \``,
            };
          }
          return {
            ans: ansFrac.numerator + ansFrac.denominator,
            str: str + `\`k + n = \``,
          };
        },
      },
      fracrecip: {
        name: "Reciprocal Fractions",
        description: "Find an unknown variable from a sum of fractions. If `a + c/x = b`, then `x = c/(b - a)`.",
        weight: 10,
        tier: 1,
        func: () => {
          const b = randomInt(2, 10);
          const a = randomInt(1, b - 1);
          const num = randomInt(1, 5);
          const d = randomInt(2, 10);
          let c = 0;
          do {
            c = randomInt(1, d - 1);
          } while (a / b == c / d);
          const frac1 = new Fraction(a, b);
          const frac2 = new Fraction(c, d);
          const denom = frac1.denominator * frac2.denominator;
          const improper =
            frac2.numerator * frac1.denominator -
            frac1.numerator * frac2.denominator;
          const ansFrac = new Fraction(num * denom, improper);
          return {
            ans: 0,
            str: `If \`${frac1.formatted()} + ${num}/x = ${frac2.formatted()}\`, then \`x = \``,
            ansArr: ansFrac.getAnswerArr(),
          };
        },
      },
      modequal: {
        name: "Modular Equivalence",
        description: "Find the value of `x` that satisfies a modular equation. Brute force the answer, then add/subtract modulus until the answer is in the correct range.",
        weight: 10,
        tier: 3,
        func: () => {
          const a = randomInt(2, 10);
          const b = randomInt(2, 10);
          const ans = randomInt(1, 20);
          let mod = 0;
          do {
            mod = randomInt(6, 20);
          } while ((ans * a) % mod == 0 || gcd(a, mod) != 1);
          return {
            ans: ans,
            str: `Find \`x, ${Math.floor(ans / mod) * mod} <= x <= ${
              Math.floor((ans + mod) / mod) * mod - 1
            },\` if \`${a}x + ${b} ~= ${((a * ans) % mod) + b} (mod ${mod})\``,
          };
        },
      },
      diffsquares: {
        name: "Difference of Squares",
        description: "Difference of squares. `a^2 - b^2 = (a + b)(a - b)`.",
        weight: 20,
        tier: 0,
        func: () => {
          const a = randomInt(20, 60);
          const b = a + randomInt(1, 10) * Math.sign(random() - 0.5);
          return {
            ans: a * a - b * b,
            str: `\`${a}^2 - ${b}^2 = \``,
          };
        },
      },
      fracsub: {
        name: "Fraction Subtraction",
        description: "Subtract two fractions. Find different strategies for speeding up the process.",
        weight: 10,
        tier: 0,
        func: () => {
          const b = randomInt(2, 9);
          let a = 0;
          do {
            a = randomInt(1, 4 * b - 1);
          } while (a % b === 0);
          const d = randomInt(2, 7);
          let c = 0;
          do {
            c = randomInt(1, 3 * d - 1);
          } while (c % d === 0);
          const frac1 = new Fraction(a, b);
          const frac2 = new Fraction(c, d);
          const denom = frac1.denominator * frac2.denominator;
          const improper =
            frac1.numerator * frac2.denominator -
            frac2.numerator * frac1.denominator;
          const ansFrac = new Fraction(improper, denom);
          return {
            ans: 0,
            str: `\`${frac1.formatted()} - ${frac2.formatted()}\` (${
              ansFrac.isMixed() ? "mixed" : "proper"
            })`,
            ansStr: ansFrac.formatted(),
          };
        },
      },
      fracdiv: {
        name: "Fraction Division",
        description: "Divide two fractions. Multiply by the reciprocal of the divisor. Be sure to simplify.",
        weight: 10,
        tier: 0,
        func: () => {
          const d1 = randomInt(2, 12);
          const d2 = randomInt(2, 12);
          const n1 = randomInt(1, d1 - 1);
          const n2 = randomInt(1, d2 - 1);
          return {
            ans: 0,
            str: `\`${new Fraction(n1, d1).formatted()} -: ${new Fraction(
              n2,
              d2
            ).formatted()} = \``,
            ansArr: new Fraction(n1 * d2, n2 * d1).getAnswerArr(),
          };
        },
      },
      multadd: {
        name: "Multiplication With Squared Sum",
        description: "Broken up multiplication with a squared sum. If `a xx b + b^2`, the answer is `(a + b)^2`. If `a xx b - b^2`, the answer is `(a - b)^2`.",
        weight: 10,
        tier: 0,
        func: () => {
          const a = Math.pow(10, randomInt(1, 2)) * randomInt(3, 30);
          const b = randomInt(4, 20);
          if (random() < 0.5) {
            return {
              ans: a * b,
              str: `\`${a + b} xx ${b} - ${b}^2 = \``,
            };
          }
          return {
            ans: a * b,
            str: `\`${a - b} xx ${b} + ${b * b} = \``,
          };
        },
      },
      binomnum: {
        name: "Binomial Number Expansion",
        description: "Find the value of a square/cube of a number. If the number is `(a * 100 + b)^c`, treat it as a binomial expansion and calculate using pascal's triangle and applying exponents to the coefficients. " +
          "Each \"term\" is 2 digits, but watch out for carry overs.",
        weight: 10,
        tier: 3,
        func: () => {
          const pow = randomInt(2, 3);
          const a = randomInt(1, 9);
          const b = randomInt(1, 9);
          const num = a * 100 + b;
          return {
            ans: Math.pow(num, pow),
            str: `\`(${num})^${pow} = \``,
          };
        },
      },
      varies: {
        name: "Function Relationships",
        description: "Given a direct or inverse relationship, find the value of a variable. Let `x_1` and `y_1` be the given values. For direct relationships, `y = (y_1/x_1) * x`. For inverse relationships, `y = (y_1 * x_1) / x`.",
        weight: 10,
        tier: 2,
        func: () => {
          const a = randomInt(3, 20);
          const b = randomInt(3, 20);
          let c = 0;
          do {
            c = randomInt(3, 20);
          } while (c == a);
          if (random() < 0.5) {
            return {
              ans: 0,
              str: `Given \`y\` varies directly with \`x\` and \`y=${b}\` when \`x=${a}\`. Find y when \`x = ${c}\``,
              ansArr: new Fraction(b * c, a).getAnswerArr(),
            };
          }
          return {
            ans: 0,
            str: `Given \`y\` varies inversely with \`x\` and \`y=${b}\` when \`x=${a}\`. Find y when \`x = ${c}\``,
            ansArr: new Fraction(b * a, c).getAnswerArr(),
          };
        },
      },
      numdivis: {
        name: "Number of Multiples",
        description: "Find the number of integers between two numbers that are divisible by a given value. Let `a` and `b` be the furthest apart multiples of `c` within the range. The answer is `(b - a) / c + 1`.",
        weight: 10,
        tier: 1,
        func: () => {
          const mod = randomInt(3, 12);
          const a = randomInt(3, 20);
          const b = randomInt(a + mod * 7, a + mod * 12);
          return {
            ans: Math.floor((b - 1) / mod) - Math.ceil((a + 1) / mod) + 1,
            str: `How many integers between \`${a}\` and \`${b}\` are divisible by \`${mod}\`?`,
          };
        },
      },
      roman: {
        name: "Roman Numerals",
        description: "Add or subtract two roman numerals. Convert each numeral to an arabic number, then convert the result back to a roman numeral.",
        weight: 10,
        tier: 0,
        func: () => {
          const a = randomInt(1, 2) * 1000 + randomInt(1, 90);
          const b = randomInt(1, 9) * 100 + randomInt(1, 90);
          const aStr = toRoman(a);
          const bStr = toRoman(b);
          if (random() < 0.5) {
            return {
              ans: a + b,
              str: `${aStr} \`+\` ${bStr} \`=\` (Arabic Numeral)`,
            };
          }
          return {
            ans: a - b,
            str: `${aStr} \`-\` ${bStr} \`=\` (Arabic Numeral)`,
          };
        },
      },
      setint: {
        name: "Set Intersection",
        description: "Count number of unique elements in an intersection of two unions of sets. Scan each element in each side and check if it exists in the other.",
        weight: 10,
        tier: 1,
        func: () => {
          const arr1 = Array(randomInt(2, 5))
            .fill(0)
            .map((v, _) => String.fromCharCode(97 + randomInt(0, 25)));
          const arr2 = Array(randomInt(2, 5))
            .fill(0)
            .map((v, _) => String.fromCharCode(97 + randomInt(0, 25)));
          const arr3 = Array(randomInt(2, 5))
            .fill(0)
            .map((v, _) => String.fromCharCode(97 + randomInt(0, 25)));
          const arr4 = Array(randomInt(2, 5))
            .fill(0)
            .map((v, _) => String.fromCharCode(97 + randomInt(0, 25)));
          const seta = new Set(arr1.concat(arr2));
          const setb = new Set(arr3.concat(arr4));
          let ans = 0;
          seta.forEach((v) => {
            if (setb.has(v)) ans++;
          });
          return {
            ans: ans,
            str: `\`[{\`${arr1.join(", ")}\`}uu{\`${arr2.join(
              ", "
            )}\`}]nn[{\`${arr3.join(", ")}\`}uu{\`${arr4.join(
              ", "
            )}\`}]\` contains how many distinct elements?`,
          };
        },
      },
      basefrac: {
        name: "Base Fractions",
        description: "Convert a base `b` decimal to a base 10 fraction, or vice versa. For a base `b` decimal, convert it into base 10 and divide by `b^c` where `c` is the number of digits after the decimal point. " +
          "For a base 10 fraction, convert the numerator and denominator into base `b` and simplify.",
        weight: 10,
        tier: 3,
        func: () => {
          const base = randomInt(4, 9);
          let num = 0;
          do {
            num = randomInt(base + 1, base * base - 1);
          } while (gcd(num, base) != 1);
          const frac = new Fraction(num, base * base);
          const a = parseInt(num.toString(base));
          if (random() < 0.5) {
            return {
              ans: 0,
              str: `\`${a / 100}_${base} =\`base 10 (fraction)`,
              ansArr: [frac.formatted(), frac.formatted({ useImproper: true })],
            };
          }
          return {
            ans: a / 100,
            str: `Change \`${frac.formatted()}\` to a base \`${base}\` decimal`,
          };
        },
      },
      quadvert: {
        name: "Quadratic Vertex",
        description: "Find the vertex of a quadratic function. For `ax^2 + bx + c`, the vertex is at `(-b/(2a), -b^2/(4a) + c)`. The sum of the y coordinates is `(-b(b + 2))/(4a) + c`.",
        weight: 10,
        tier: 3,
        func: () => {
          const a = Math.max(randomInt(-2, 2), 1) * Math.sign(random() - 0.5);
          const b = randomInt(1, 8) * Math.sign(random() - 0.5);
          const c = randomInt(1, 8) * Math.sign(random() - 0.5);
          const denom = 4 * a;
          // const vert = -b / (2 * a);
          if (random() < 0.4) {
            return {
              ans: 0,
              str: `The ${a > 0 ? "minimum" : "maximum"} value of \`${
                (a < 0 ? "-" : "") + (Math.abs(a) > 1 ? Math.abs(a) : "")
              }x^2${
                (b < 0 ? "-" : "+") + (Math.abs(b) > 1 ? Math.abs(b) : "")
              }x${(c < 0 ? "-" : "+") + Math.abs(c)}\` is`,
              ansArr: new Fraction(
                -b * b + c * denom,
                denom
              ).getAnswerArr(),
            };
          }
          return {
            ans: 0,
            str: `Given: \`f(x)=${
              (a < 0 ? "-" : "") + (Math.abs(a) > 1 ? Math.abs(a) : "")
            }x^2${(b < 0 ? "-" : "+") + (Math.abs(b) > 1 ? Math.abs(b) : "")}x${
              (c < 0 ? "-" : "+") + Math.abs(c)
            }\` has a ${
              a > 0 ? "minimum" : "maximum"
            } point at \`(a, b)\`. Find \`a + b\`.`,
            ansArr: new Fraction(
              -b * (b + 2) + c * denom,
              denom
            ).getAnswerArr(),
          };
        },
      },
      quadroot: {
        name: "Squared Roots",
        description: "Find the root of an equation in the form `(ax + b)^2 = c`. The larger root is `(sqrt(c) - b) / a` and the smaller root is `(-sqrt(c) - b) / a`.",
        weight: 10,
        tier: 2,
        func: () => {
          const a = randomInt(1, 5);
          const b = randomInt(1, 5) * Math.sign(random() - 0.5);
          const numer = randomInt(1, 5);
          const denom = random() > 0.5 ? 1 : randomInt(2, 5);
          const frac = new Fraction(Math.pow(numer, 2), Math.pow(denom, 2));
          if (random() < 0.5) {
            return {
              ans: 0,
              str: `The larger root of \`(${a > 1 ? a : ""}x ${
                b > 0 ? "+" : "-"
              } ${Math.abs(b)})^2 = ${frac.formatted()}\` is`,
              ansArr: new Fraction(numer - b * denom, denom * a).getAnswerArr(),
            };
          }
          return {
            ans: 0,
            str: `The smaller root of \`(${a > 1 ? a : ""}x ${
              b > 0 ? "+" : "-"
            } ${Math.abs(b)})^2 = ${frac.formatted()}\` is`,
            ansArr: new Fraction(-numer - b * denom, denom * a).getAnswerArr(),
          };
        },
      },
      fracest: {
        name: "Fraction Estimation",
        description: "Estimate an expression with fractions or decimals. The pure estimation test.",
        weight: 20,
        tier: 3,
        func: () => {
          const a = randomInt(100, 900);
          const b = randomInt(2, 15);
          let c = 0;
          do {
            c = randomInt(2, 15);
          } while (gcd(b, c) != 1 || c % 5 == 0 || c % 2 == 0);
          const d = randomInt(2, 15);
          let e = 0;
          do {
            e = randomInt(2, 15);
          } while (gcd(d, e) != 1);
          return {
            ans: (((a * c) / b) * d) / e,
            str: `*\`${a} -: ${(b / c).toFixed(4)}... xx ${new Fraction(
              d,
              e
            ).formatted()} = \``,
            guess: true,
          };
        },
      },
      systems: {
        name: "Systems of Equations",
        description: "Solve a system of equations. Use substitution or elimination to find the value of each variable. If given `x - y = a` and `x + y = b`, `x^2 + y^2 = (a^2 + b^2) / 2`.",
        weight: 20,
        tier: 1,
        func: () => {
          const x = randomInt(1, 5) * Math.sign(random() - 0.4);
          const y = randomInt(1, 5) * Math.sign(random() - 0.4);
          if (random() < 0.25) {
            return {
              ans: x * x + y * y,
              str: `If \`x + y = ${x + y}\` and \`x - y = ${
                x - y
              }\`, then \`x^2 + y^2 = \``,
            };
          }
          const a = randomInt(1, 4);
          const b = Math.max(randomInt(-3, 2), 1);
          const c = randomInt(1, 4);
          const d = Math.max(randomInt(-3, 2), 1);
          const str = `If \`${a > 1 ? a : ""}x + ${b > 1 ? b : ""}y = ${
            a * x + b * y
          }\` and \`${c > 1 ? c : ""}x - ${d > 1 ? d : ""}y = ${
            c * x - d * y
          }\`, then `;
          switch (randomInt(0, 1)) {
            case 0:
              return {
                ans: x,
                str: str + "`x = `",
              };
            default:
              return {
                ans: y,
                str: str + "`y = `",
              };
          }
        },
      },
      focus: {
        name: "Focus of a Parabola",
        description: "Find the focus of a parabola. The focus of `y = a(x - h)^2 + k` is `(h, k + 1/(4a))`.",
        weight: 10,
        tier: 3,
        func: () => {
          const numer =
            Math.max(randomInt(-1, 4), 1) * Math.sign(random() - 0.5);
          const denom = numer == 1 ? randomInt(1, 4) : 1;
          const a = new Fraction(numer, denom);
          const h = randomInt(-5, 5);
          const k = randomInt(-5, 5);
          const ans = new Fraction(
            a.denominator + 4 * k * a.numerator,
            4 * a.numerator
          ).getAnswerArr();
          let str = "";
          switch (randomInt(0, 1)) {
            case 0:
              str = `Let \`(x, y)\` be the focus of \`y = ${
                numer == denom ? "" : numer == -denom ? "-" : a.formatted()
              }${
                h == 0 ? `x^2` : `(x ${h > 0 ? "-" : "+"} ${Math.abs(h)})^2`
              } ${
                k == 0 ? "" : `${k > 0 ? "+" : "-"} ${Math.abs(k)}`
              }\`. \`y = \``;
              break;
            case 1:
              str = `Let \`(x, y)\` be the focus of \`x = ${
                numer == denom ? "" : numer == -denom ? "-" : a.formatted()
              }${
                h == 0 ? `y^2` : `(y ${h > 0 ? "-" : "+"} ${Math.abs(h)})^2`
              } ${
                k == 0 ? "" : `${k > 0 ? "+" : "-"} ${Math.abs(k)}`
              }\`. \`x = \``;
              break;
          }
          return {
            ans: 0,
            str: str,
            ansArr: ans,
          };
        },
      },
      deriv: {
        name: "Derivatives",
        description: "Find the derivative of a function. Use the power rule and arithmetic.",
        weight: 10,
        tier: 3,
        func: () => {
          const a = randomInt(1, 5) * Math.sign(random() - 0.5);
          const b = randomInt(1, 5) * Math.sign(random() - 0.5);
          const c = randomInt(1, 5) * Math.sign(random() - 0.5);
          const x = randomInt(1, 5) * Math.sign(random() - 0.5);
          return {
            ans: 2 * a * x + b,
            str: `Let \`f(x) = ${
              (a < 0 ? "-" : "") + (Math.abs(a) > 1 ? Math.abs(a) : "")
            }x^2${(b < 0 ? "-" : "+") + (Math.abs(b) > 1 ? Math.abs(b) : "")}x${
              (c < 0 ? "-" : "+") + Math.abs(c)
            }\`. \`f^'(${x}) = \``,
          };
        },
      },
      words: {
        name: "Word Conversions",
        description: "Convert a number from words into digits. Keep track of the place values.",
        weight: 10,
        tier: 0,
        func: () => {
          // hundred or ten millions, fifths of millions, thousands, tens and ones
          const a = randomInt(2, 9) * Math.pow(10, randomInt(1, 2));
          const fifths = randomInt(1, 4);
          const b = randomInt(1, 9);
          const ones = randomInt(20, 90);
          return {
            ans: a * 1000000 + fifths * 200000 + b * 1000 + ones,
            str: `Write ${
              a > 100 ? names[a / 100] + " hundred" : tens[a / 10]
            } million ${names[fifths]}-fifths million ${names[b]} thousand ${
              tens[Math.floor(ones / 10)]
            }${ones % 10 > 0 ? "-" + names[ones % 10] : ""} in digits`,
          };
        },
      },
      estadd: {
        name: "Addition Estimation",
        description: "Estimate the sum of integers",
        weight: 20,
        tier: 0,
        func: () => {
          const nums = Math.max(randomInt(1, 5), 3);
          const arr: number[] = [];
          for (let i = 0; i < nums; i++) {
            const n =
              Math.floor(
                randomInt(10000, 99999) / Math.pow(10, randomInt(0, 2))
              ) * Math.sign(random() - 0.5);
            arr.push(n);
          }
          arr[0] = Math.abs(arr[0]);
          const ans = arr.reduce((a, b) => a + b, 0);
          let str = `*\`${arr[0]}`;
          for (const n of arr.slice(1)) {
            str += `${n > 0 ? " + " : " - "}${Math.abs(n)}`;
          }
          str += ` =\``;
          return {
            ans: ans,
            str: str,
            guess: true,
          };
        },
      },
      estmult: {
        name: "Multiplication Estimation",
        description: "Estimate the product of integers. Round each number a bit, multiply, then adjust if needed.",
        weight: 10,
        tier: 0,
        func: () => {
          const aDigits = randomInt(2, 4);
          const a = Math.floor(
            randomInt(1000, 9999) / Math.pow(10, 4 - aDigits)
          );
          const b = Math.floor(
            randomInt(1000, 9999) / Math.pow(10, aDigits - 2)
          );
          return {
            ans: a * b,
            str: `*\`${a} xx ${b} =\``,
            guess: true,
          };
        },
      },
      squareperim: {
        name: "Area Change from Perimeter",
        description: "Find the change in area when the perimeter of a square is increased/decreased. Let `p_1` and `p_2` be the perimeters of the squares. The change in area is `((p_2)^2 - (p_1)^2) / 16` or `((p_2) / 4)^2 - ((p_1) / 4)^2`.",
        weight: 10,
        tier: 2,
        func: () => {
          const p1 = randomInt(10, 20);
          const p2 = randomInt(p1 + 2, p1 + 10);
          if (random() < 0.5) {
            return {
              ans: 0,
              str: `If the perimeter of a square is decreased from \`${p2}\` to \`${p1}\`, the decrease in area is`,
              ansArr: new Fraction(p2 * p2 - p1 * p1, 16).getAnswerArr(),
            };
          }
          return {
            ans: 0,
            str: `If the perimeter of a square is increased from \`${p1}\` to \`${p2}\`, the increase in area is`,
            ansArr: new Fraction(p2 * p2 - p1 * p1, 16).getAnswerArr(),
          };
        }
      },
      sumratcoef: {
        name: "Sum of Rational Coefficients",
        description: "Find the sum of the coefficients of a rational function. For each `(ax + b)` term, replace it with the sum `a + b`. Then add all terms as if they were fractions.",
        weight: 10,
        tier: 3,
        func: () => {
          // Pairs of numer, numer, denom, denom
          const nums = Array(8).fill(0).map((_, i) => randomInt(1, 5) * Math.sign(random() - 0.5));
          for (let i = 0; i < 8; i += 2) {
            if (Math.random() < .5) {
              nums[i] = 1;
            }
            if (i != 2 && nums[i] < 0) {
              nums[i] *= -1;
            }
            if (nums[i] + nums[i + 1] == 0) {
              if (nums[i + 1] == -1) {
                nums[i + 1] += Math.sign(random() - 0.5) * 2;
              } else {
                nums[i + 1] += Math.sign(random() - 0.5);
              }
            }
            while (nums[5] == nums[7] && nums[4] == nums[6]) {
              nums[5] += Math.sign(random() - 0.5);
            }
          }
          const xStrs = nums.filter((_, i) => i % 2 == 0).map((n, i) => `${n > 1 ? n : ""}x ${nums[i * 2 + 1] > 0 ? "+" : "-"} ${Math.abs(nums[i * 2 + 1])}`);
          // Sum of the pairs
          const sums = Array(4).fill(0);
          for (let i = 0; i < 4; i++) {
            sums[i] = nums[i * 2] + nums[i * 2 + 1];
          }
          const numer = sums[0] * sums[3] + sums[1] * sums[2];
          const denom = sums[2] * sums[3];
          const ans = numer + denom;
          const str1 = `(${xStrs[0]})/(${xStrs[2]})`;
          if (nums[2] < 0) {
            return {
              ans: ans,
              str: `If \`${str1} - (${-nums[2] > 1 ? -nums[2] : ""}x ${nums[3] < 0 ? "+" : "-"} ${Math.abs(nums[3])})/(${xStrs[3]}) = (ax^2 + bx + c) / (dx^2 + ex + f)\`, then \`a + b + c + d + e + f = \``,
            }
          }
          return {
            ans: ans,
            str: `If \`${str1} + (${xStrs[1]})/(${xStrs[3]}) = (ax^2 + bx + c) / (dx^2 + ex + f)\`, then \`a + b + c + d + e + f = \``
          }
        }
      },
      chainrule: {
        name: "Chain Rule",
        description: "Find the derivative of a `(ax + b)^c` function. Use the chain rule to get the answer `c * a * (ax + b)^(c - 1)`.",
        weight: 10,
        tier: 3,
        func: () => {
          const a = randomInt(1, 5);
          const b = randomInt(1, 5) * Math.sign(random() - 0.5);
          const c = randomInt(2, 5);
          const x = randomInt(1, 5) * Math.sign(random() - 0.5);
          return {
            ans: c * a * Math.pow(a * x + b, c - 1),
            str: `Let \`f(x) = (${a > 1 ? a : ""}x ${b > 0 ? "+" : "-"} ${Math.abs(b)})^${c}\`. \`f^'(${x}) = \``,
          };
        }
      },
      varsum: {
        name: "Sum of Variable Sequence",
        description: "Find a certain term giving a sequence `x + (x + a) + (x + 2a) + ... + (x + (n - 1)a)` and the sum. Find the number of terms and calculate the desired term.",
        weight: 6,
        tier: 1,
        func: () => {
          const a = randomInt(1, 4);
          const num = (a % 2 === 0 ? randomInt(4, 10) : randomInt(2, 5) * 2);
          const mid = randomInt(4, 10);
          const sum = num * mid;
          const x = mid - a * (num - 1) / 2;
          const term = randomInt(1, num - 1);
          const ans = x + a * term;
          return {
            ans: ans,
            str: `Given the sequence \`x + (x + ${a}) + (x + ${2 * a}) + ${num > 4 ? "... + " : ""} (x + ${(num - 1) * a}) = ${sum}\`, what is the value of the \`(x + ${a * term})\` term.`,
          }
        }
      },
      perfect: {
        name: "Perfect Numbers",
        description: "Memorize your perfect numbers. 6, 28, 496, 8148, ...",
        weight: 4,
        tier: 1,
        func: () => {
          const perfects = [6, 28, 496, 8128];
          if (random() < .33) {
            // Choose perfect number out of random set
            const n = randomInt(3, 5);
            const arr = Array(n - 1).fill(1);
            const used = new Set();
            for (let i = 0; i < n - 1; i++) {
              const factorCount = randomInt(2, 5);
              for (let j = 0; j < factorCount; j++) {
                arr[i] *= randomInt(2, 7);
              }
              while (perfects.includes(arr[i]) || used.has(arr[i])) {
                arr[i] += 2;
              }
              used.add(arr[i]);
            }
            const val = perfects[randomInt(0, perfects.length - 1)];
            arr.push(val);
            arr.sort((a, b) => a - b);
            return {
              ans: val,
              str: `Which of the following is a perfect number? {${arr.join(", ")}}`,
            }
          }
          if (random() < .5) {
            // Choose not perfect number out of a random set
            const arr: number[] = [];
            const used = new Set();
            for (let i = 0; i < 2; i++) {
              let perf = 0;
              do {
                perf = perfects[randomInt(0, perfects.length - 1)];
              } while (used.has(perf));
              arr.push(perf);
              used.add(perf);
            }
            const factorCount = randomInt(2, 5);
            let val = 1;
            for (let j = 0; j < factorCount; j++) {
              val *= randomInt(2, 7);
            }
            if (perfects.includes(val)) {
              val += 2;
            }
            arr.push(val);
            arr.sort((a, b) => a - b);
            return {
              ans: val,
              str: `Which of the following is not a perfect number? {${arr.join(", ")}}`,
            }
          }
          // Determine nth perfect number
          const index = randomInt(0, perfects.length - 1);
          return {
            ans: perfects[index],
            str: `What is the ${getNumberRankStr(index + 1)} perfect number?`,
          }
        }
      },
      unitconv: {
        name: "Unit Conversion",
        description: "Common unit conversions. 1 fathom = 6 feet. 1 rod = 16.5 feet. 15 mph = 22 ft/s. 1 mile^2 = 640 acres.",
        weight: 5,
        tier: 1,
        func: () => {
          const index = randomInt(0, units.length - 1);
          const val = randomInt(4, 20) / 2;
          const main = randomInt(0, 1);
          return {
            ans: val * convs[index][main],
            str: `${val * convs[index][main ^ 1]} ${units[index][main ^ 1]} \`=\` ? ${units[index][main]}`,
          }
        }
      },
      unitconvest: {
        name: "Unit Conversion Estimation",
        description: "Estimate common unit conversions. 1 league of land = 4428.4 acres. 1 gallon = 231 in^3. 1 vara in Texas is 100/3 inches or 25/27 yards. 1 chain is 66 feet. 1 caballerias is 108 acres. 1 labor is 1000 square varas. For more conversions, see Unit Conversion section.",
        weight: 5,
        tier: 2,
        func: () => {
          const index = randomInt(0, units.length - 1);
          const val = randomInt(10, 400);
          const main = randomInt(0, 1);
          return {
            ans: val * convs[index][main],
            str: `${val * convs[index][main ^ 1]} ${units[index][main ^ 1]} \`=\` ? ${units[index][main]}`,
            guess: true,
          }
        }
      },
      digitsum: {
        name: "3 Digit Sum",
        description: "The number of 3 digit numbers that have a digit sum to n. For 1 through 9, the answer is its triangular number. For 10 - 14, its 54, 61, 66, 69, and 70. Note that number of 3 digit numbers that have a digit sum of n is the same as that of 28 - n.",
        weight: 5,
        tier: 2,
        func: () => {
          const num = Math.floor(Math.random() * 27);
          const values = [1, 3, 6, 10, 15, 21, 28, 36, 45, 54, 61, 66, 69, 70];
          return{
             ans: num < 14 ? values[num] : values[26 - num],
             str: `The sum of the digits of a 3 digit number is \`${num + 1}\`. How many such numbers exist?`,

          }
        }
      },

      linereflect: {
        name: "Line Reflection",
        description: "Reflect a point (a,b) across the x axis, y axis, or y = x, and finding the sum/difference of a and b. The reflection across the x axis is (a,-b), the y axis is (-a,b), and y = x is (b,a).",
        weight: 5,
        tier: 2,
        func: () => {
          const lines = ["x-axis", "y-axis", "y = x"];
          const operations = ["a - b", "a + b", "b - a", "b + a"];
          let a = randomInt(-10, 10);
          let b = randomInt(-10, 10);
          const line = lines[randomInt(0, lines.length - 1)];
          const operation = operations[randomInt(0, operations.length - 1)];
          let ans = 0;
          let str = `Reflect the point \`(${a}, ${b})\` across the \`${line}\` and find the value of ${operation}.`;
          switch (line) {
            case "x-axis":
              b = -b;
              break;
            case "y-axis":
              a = -a;
              break;
            case "y = x":
              let temp = b;
              b = a;
              a = temp;
              break;
          }
          switch (operation) {
            case "a - b":
              ans = a - b;
              break;
            case "a + b":
              ans = a + b;
              break;
            case "b - a":
              ans = b - a;
              break;
            case "b + a":
              ans = b + a;
              break;
          }
          return{
             ans: ans,
             str: str,

          }
        }
      },

      fermatlittle: 
      {
        name: "Fermat's Little Theorem",
        description: "If p is prime, then a^(p - 1) = 1 (mod p). Additionally, for specific prime p, a^((p-1)/2) = -1 (mod p)" ,
        weight: 5,
        tier: 2,
        func: () => {
          const primes = [17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59];
          const prime = primes[randomInt(0, primes.length - 1)];
          const exp = (prime - 1) / 2;
          const add = randomInt(0, 2);
          const quadres = new Set<number>();
          for (let i = 1; i < prime; i++) 
          {
            quadres.add((i * i) % prime);
          }
          let nums: number[] = [];
          for(let i = 1; i < prime; i++)
          {
            if(!quadres.has(i)) nums.push(i);
          }
          const num = nums[randomInt(0, nums.length - 1)];
          const exp2 = exp + add;
          let ans = (-1 * Math.pow(num, add)) % prime;
          if (ans < 0) ans += prime;
          return{
              ans: ans,
              str: `Find the value of \`${num}^(${exp2}) \`mod ${prime}.\``,
          }
        }
      }
    };

    const keys = Object.keys(this.questionGens);
    this.tiers = [[], [], [], []];
    for (const key of keys) {
      this.tiers[this.questionGens[key].tier].push(key);
    }
  }

  generateQuestion(
    modeData: ModeData,
    filterKeys: string[] = Object.keys(this.questionGens),
    tier = -1
  ): ModeQuestion {
    const { random, randomInt } = this.randoms;
    const print = tier != -1;
    // if (tier === -1 && modeData.gameMode !== "Test") {
    //   tier = Math.min(Math.floor(modeData.total / getTestLength() * 4), tiers.length - 1);
    //   print = false;
    // }
    let question, key;
    if (modeData.gameMode === "Zetamac") {
      const available = ["add", "sub", "mult", "div"].filter((key) =>
        filterKeys.includes(key)
      );
      if (available.length === 0)
        available.push(...["add", "sub", "mult", "div"]);
      const rand = randomInt(1, available.length);
      key = available[rand - 1];
      if (key === "add") question = this.questionGens.add.func(2, 100);
      else if (key === "sub") question = this.questionGens.sub.func(2, 100);
      else if (key === "mult")
        question = this.questionGens.mult.func(2, 12, 100);
      else question = this.questionGens.div.func(2, 100, 12);
    } else if (modeData.gameMode === "Estimate") {
      const available = [
        "sqrt",
        "cbrt",
        "estmult",
        "estdiv",
        "fracest",
        "estadd",
      ].filter((key) => filterKeys.includes(key));
      if (available.length === 0)
        available.push(
          ...["sqrt", "cbrt", "estmult", "estdiv", "fracest", "estadd"]
        );
      const rand = randomInt(1, available.length);
      key = available[rand - 1];
      question = this.questionGens[key].func();
    } else if (tier != -1) {
      let totalWeight = 0;
      for (key of this.tiers[tier])
        totalWeight += this.questionGens[key].weight;
      let rand = 0;
      do {
        rand = random() * totalWeight;
        for (key of this.tiers[tier]) {
          rand -= this.questionGens[key].weight;
          if (rand < 0) break;
        }
        const questionGen = this.questionGens[key!];
        question = questionGen.func();
      } while (
        !print &&
        (question.guess === true) !=
          (Math.floor(
            (modeData.total + 1) % (modeData.testLength >= 40 ? 10 : 5)
          ) ==
            0)
      );
    } else {
      let totalWeight = 0;
      for (key of filterKeys) totalWeight += this.questionGens[key].weight;
      let rand = random() * totalWeight;
      for (key of filterKeys) {
        rand -= this.questionGens[key].weight;
        if (rand < 0) break;
      }
      const questionGen = this.questionGens[key!];
      question = questionGen.func();
    }
    // if (!useAsciiMath) {
    //   modeData.question.str = modeData.question.str.replace(/`/g, "");
    //   // also replace sqrt, cbrt
    // }
    // console.log(modeData.question.ans);
    return { category: key!, question: question };
  }
}

export function getGuessRange(value: number) {
  return `${Math.round(value - 0.05 * Math.abs(value))} — 
          ${Math.round(value + 0.05 * Math.abs(value))}`;
}

export function judgeQuestion(question: Question, str: string): AnswerJudgement {
  const n = parseFloat(str);
  let judgement: AnswerJudgement = { correct: false };
  if (question.ansStr || question.ansArr) {
    // If correct
    if (question.ansArr?.includes(str) || str === question.ansStr) {
      judgement = { correct: true };
    }
  } else if (!isNaN(n)) {
    // Check guess bounds
    if (question.guess && Math.abs(Math.round(n - question.ans) / question.ans) <= 0.05) {
      const diff = Math.abs((n - question.ans) / question.ans);
      const prefix =
        diff <= 0.01
          ? "🟦 Excellent guess!"
          : diff <= 0.03
          ? "🟩 Great guess!"
          : "🟨 Good guess!";
      judgement = {
        correct: true,
        other: `${prefix} ${(diff * 100).toFixed(1)}% off. ${getGuessRange(question.ans)}`,
      };
    } else if (n === question.ans) {
      judgement = { correct: true };
    }
  }
  return judgement;
}

export function calculateScore(correct: number, answered: number) {
  return answered * 5 - (answered - correct) * 9;
}

export function calculateAdjustedScore(
  correct: number,
  answered: number,
  test_length: number
) {
  return calculateScore(correct, answered) * (80 / test_length);
}

export function getAnswerDisplay(question: Question) {
  if (question.guess) return getGuessRange(question.ans);
  if (question.ansArr) return question.ansArr.join(" or ");
  if (question.ansStr) return question.ansStr;
  return question.ans.toString();
}
