// DO NOT EDIT THIS FILE OUTSIDE OF BACKEND

import { Pool } from "pg";
import { AnswerJudgement, GameMode, gameModeMappings, getNumQuestions, getTestDuration, LeaderboardEntry, ModeData, Question, testLengths, TestResults, UserData } from "./types";
import { calculateAdjustedScore, judgeQuestion, QuestionGeneratorList, RNG } from "./generator";
import { decryptSeed } from "./encrypt";
import { Filter } from 'bad-words';

export const pool = new Pool();

export const filter = new Filter();

// Fetch leaderboard of specific game mode
export async function getLeaderboard(leaderboardKey: string | null, test_length: number): Promise<LeaderboardEntry[]> {
    if (!leaderboardKey || !Object.values(gameModeMappings).includes(leaderboardKey))
        return [];
    return (await pool.query(`
        SELECT user_id, correct, answered, test_length, adjusted, time, username FROM (
            SELECT DISTINCT ON (user_id) user_id, adjusted, time FROM leaderboard WHERE mode = $1 AND test_length = $2 ORDER BY user_id, adjusted DESC, time ASC
        ) AS top_entries
        JOIN leaderboard USING (user_id, adjusted, time)
        JOIN user_auth USING (user_id)
        ORDER BY adjusted DESC, time ASC
        LIMIT 10
        `,
        [leaderboardKey, test_length])).rows;
}

// Fetch data of a user
export async function getUserData(user_id: number): Promise<UserData | null> {
    if (!user_id)
        return null;
    const result = await pool.query("SELECT user_id, tests_taken, questions_answered, questions_correct, wins, username FROM user_data JOIN user_auth USING (user_id) WHERE user_id = $1", [user_id]);
    return result.rows.length ? result.rows[0] : null;
}

// Generate random test questions with the given seed
export function getTestQuestions(seed: string, gameMode: GameMode, testLength: number) {
    const questionGen = new QuestionGeneratorList(new RNG(seed));
    const modeData: ModeData = {lastT: Date.now(), total: 0, testLength: testLength, question: {ans: 0, str: ""}, enterMode: "Test", gameMode: gameMode};
    const questions: Question[] = [];
    for (let offset = 0; offset < testLength; offset++) {
        const shouldBeEstimate = gameMode === "Estimate" || gameMode === "Number Sense" && (offset + 1) % 10 == 0;
        let question: Question;
        do {
            question = questionGen.generateQuestion(modeData, undefined, Math.floor(offset / (testLength / 4))).question;
        }
        while ((question.guess === true) != shouldBeEstimate);
        modeData.total++;
        questions.push(question);
        // const isGuess = question.guess;
        // if (isGuess)
            // question.str = question.str.replace("*", "");
    }
    return questions;
}

// Submit graded test to the leaderboard
export async function submitLeaderboardEntry(gameMode: GameMode, entry: LeaderboardEntry) {
    await pool.query(`INSERT INTO leaderboard (user_id, correct, answered, test_length, adjusted, time, mode, timestamp, seed) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`, [entry.user_id, entry.correct, entry.answered, entry.test_length, entry.adjusted, entry.time, gameModeMappings[gameMode], entry.timestamp, entry.seed]);
    await pool.query("UPDATE user_data SET tests_taken = tests_taken + 1, questions_answered = questions_answered + $2, questions_correct = questions_correct + $3 WHERE user_id = $1", [entry.user_id, entry.answered, entry.correct]);
}

interface Submission {
    testLength: number;
    gameMode: string;
    answers: string[];
    id: string;
};

const minAvgTimePerQuestion = {
    "Number Sense": 1.8,
    "Zetamac": .58,
    "Estimate": 2.9
};

export async function handleSubmit(body: FormData, user_id: number): Promise<TestResults | null> {
    let submission: Submission | null = null;
    try {
        const testLength = parseInt(body.get("testLength") as string);
        const gameMode = body.get("mode") as string;
        const id = body.get("id") as string;
        // const testLength = isValidTestLength(testOptions.testLength);
        // const gameMode = gameModes.find(gm => gameModeMappings[gm] === body.mode);
        // const id = BigInt(body.id);
        const answers = Array(testLength).fill(0).map((_, i) => body.get(`q${i}`) as string);
        // Validate fields
        if (!testLength || !gameMode || !answers || answers.length !== testLength || 
            !answers.every((s: string) => typeof s === "string") || !testLengths.includes(testLength) || !gameModeMappings[gameMode])
            throw "Bad";
        submission = {testLength: testLength, gameMode: gameMode, answers: answers, id: id};
    }
    catch {}
    // If error parsing client request, then return Bad Request
    if (!submission || typeof submission != "object") {
        return null;
    }
    // Grade submission
    let correct = 0;
    let answered = 0;
    let hasAnsweredQuestion = false;

    // Check if submitted in time
    const testDuration = getTestDuration(submission.gameMode, submission.testLength);
    const { seed, time } = decryptSeed(submission.id);
    if (Date.now() - time > 10 * 1000 + testDuration) {
        console.warn(user_id, "took too long to submit");
        return null;
    }

    const timeTaken = Math.min(Date.now() - time, testDuration) / 1000;
    const questions = getTestQuestions(seed, submission.gameMode, getNumQuestions(submission.gameMode, submission.testLength));
    const judgements: AnswerJudgement[] = [];
    for (let i = submission.testLength - 1; i >= 0; i--) {
        hasAnsweredQuestion ||= submission.answers[i].length > 0;
        if (hasAnsweredQuestion) {
            answered++;
            const judgement = judgeQuestion(questions[i], submission.answers[i]);
            judgements.push(judgement);
            if (judgement.correct)
                correct++;
        }
    }
    judgements.reverse();
    
    const score = submission.gameMode === "Zetamac" ? correct / submission.testLength * 120 : calculateAdjustedScore(correct, answered, submission.testLength);
    const entry: LeaderboardEntry = { user_id: user_id, correct: correct, answered: answered, test_length: submission.testLength, adjusted: score, time: timeTaken, timestamp: new Date(), seed: seed };
    
    // Do not submit to leaderboard if taking test as guest (user_id = 0)
    // Do not add to leaderboard if user has not answered at least half of the questions or if the user gets less than 50% correct
    // Ignore if time is unreasonable (only if high accuracy)
    if (user_id && (entry.answered * 2 >= entry.test_length && entry.correct * 2 >= entry.answered) && (correct / answered <= .7 || timeTaken / answered >= minAvgTimePerQuestion[submission.gameMode])) {

        const lastTest = await pool.query("SELECT timestamp, seed FROM leaderboard WHERE user_id = $1 AND timestamp IS NOT NULL ORDER BY timestamp DESC LIMIT 1", [user_id]);

        if (lastTest.rows.length == 0 || (Date.now() - lastTest.rows[0].timestamp.getTime() > 5 && lastTest.rows[0].seed !== seed)) {
            submitLeaderboardEntry(submission.gameMode, entry);
        }
    }

    return { questions: questions, judgements: judgements, answers: submission.answers, entry: entry };
    // return NextResponse.json(judgements.map((judgement, i) => `Q${i + 1}: ${questions[i].str} - ${judgement.correct ? "✔️" : `❌ (you put ${submission.answers[i]}, ans = ${getAnswerDisplay(questions[i])}`}`));
}