// DO NOT EDIT THIS FILE OUTSIDE OF BACKEND

import crypto from "crypto";

const algorithm = "aes-256-gcm";
const AES_KEY = new Uint8Array(Buffer.from(BigInt(process.env.AES_KEY!).toString(16), "hex"));
const AES_IV = new Uint8Array(Buffer.from(BigInt(process.env.AES_IV!).toString(16), "hex"));

export function encrypt(message: string) {
    const cipher = crypto.createCipheriv(algorithm, AES_KEY, AES_IV);
    return cipher.update(message, "utf8", "base64") + cipher.final("base64");
}

export function decrypt(encrypted: string) {
    const cipher = crypto.createDecipheriv(algorithm, AES_KEY, AES_IV);
    return cipher.update(encrypted, "base64", "ascii");
}

export function encryptSeed(seed: string) {
    return encrypt(JSON.stringify({ seed: seed, time: Date.now() }));
}
export function decryptSeed(encrypted: string) {
    return JSON.parse(decrypt(encrypted));
}